# Generated by Django 5.0.7 on 2024-07-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=70)),
                ("description", models.TextField()),
                ("photo", models.ImageField(upload_to="images")),
                ("price", models.FloatField(default=False)),
                ("articule", models.CharField(max_length=70)),
            ],
        ),
    ]
