# Generated by Django 5.0.7 on 2024-07-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="articule",
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
